//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 03:48:07 PM CET 
//


package eu.stork.extension.protocol;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SPInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SPInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SPID" type="{urn:eu:stork:names:tc:STORK:1.0:protocol}SPIDType"/>
 *         &lt;element name="SPCertSig" type="{urn:eu:stork:names:tc:STORK:1.0:protocol}SPCertSigType" minOccurs="0"/>
 *         &lt;element name="SPCertEnc" type="{urn:eu:stork:names:tc:STORK:1.0:protocol}SPCertEncType" minOccurs="0"/>
 *         &lt;element name="SPAuthRequest" type="{urn:eu:stork:names:tc:STORK:1.0:protocol}SPAuthRequestType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPInformationType", namespace = "urn:eu:stork:names:tc:STORK:1.0:protocol", propOrder = {
    "spid",
    "spCertSig",
    "spCertEnc",
    "spAuthRequest"
})
public class SPInformationType {

    @XmlElement(name = "SPID", required = true)
    protected String spid;
    @XmlElement(name = "SPCertSig")
    protected SPCertSigType spCertSig;
    @XmlElement(name = "SPCertEnc")
    protected SPCertEncType spCertEnc;
    @XmlElement(name = "SPAuthRequest")
    protected SPAuthRequestType spAuthRequest;

    /**
     * Gets the value of the spid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPID() {
        return spid;
    }

    /**
     * Sets the value of the spid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPID(String value) {
        this.spid = value;
    }

    /**
     * Gets the value of the spCertSig property.
     * 
     * @return
     *     possible object is
     *     {@link SPCertSigType }
     *     
     */
    public SPCertSigType getSPCertSig() {
        return spCertSig;
    }

    /**
     * Sets the value of the spCertSig property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPCertSigType }
     *     
     */
    public void setSPCertSig(SPCertSigType value) {
        this.spCertSig = value;
    }

    /**
     * Gets the value of the spCertEnc property.
     * 
     * @return
     *     possible object is
     *     {@link SPCertEncType }
     *     
     */
    public SPCertEncType getSPCertEnc() {
        return spCertEnc;
    }

    /**
     * Sets the value of the spCertEnc property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPCertEncType }
     *     
     */
    public void setSPCertEnc(SPCertEncType value) {
        this.spCertEnc = value;
    }

    /**
     * Gets the value of the spAuthRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SPAuthRequestType }
     *     
     */
    public SPAuthRequestType getSPAuthRequest() {
        return spAuthRequest;
    }

    /**
     * Sets the value of the spAuthRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPAuthRequestType }
     *     
     */
    public void setSPAuthRequest(SPAuthRequestType value) {
        this.spAuthRequest = value;
    }

}
